### ISSUE TITLE
运行cargo build --release ，遇错

### ISSUE THREAD

**Issue by briteming** [eycorsican/tun2socks-rs#1]
git clone https://github.com/eycorsican/tun2socks-rs tun2socks-rs-by-eycorsican
cd tun2socks-rs-by-eycorsican
git submodule update --init --recursive
cargo build --release
显示：
error: failed to parse manifest at `/Users/brite/tun2socks-rs-by-eycorsican/Cargo.toml`

Caused by:
  unknown cargo feature `strip`

怎么解决？

**Comment by eycorsican** [comment]
Use nightly rust:
```sh
rustup toolchain install nightly
rustup default nightly
```
And specify the package on build:
```sh
cargo build --release --package tun2socks-bin
```
